name: Deploy LIF GraphQL API to Amazon ECS

on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths:
      - .github/workflows/lif_graphql_api.yml
      - bases/lif/api_graphql/**
      - cloudformation/dev-lif-graphql.params
      - cloudformation/lif-graphql-taskdef-includes.yml
      - components/lif/mdr_client/**
      - components/lif/openapi_to_graphql/**
      - components/lif/string_utils/**
      - components/lif/logging/**
      - projects/lif_graphql_api/**
      - .github/workflows/_deploy-service.yml

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    uses: ./.github/workflows/_deploy-service.yml
    with:
      service_name: graphql
      working_dir: ./projects/lif_graphql_api
      ecr_repository: lif/dev/lif_graphql_api
      ecs_services: '["graphql-org1-FARGATE", "graphql-org2-FARGATE", "graphql-org3-FARGATE"]'
