name: Deploy LIF Query Planner API to Amazon ECS

on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths:
      - .github/workflows/lif_query_planner_api.yml
      - bases/lif/query_planner_restapi/**
      - cloudformation/dev-lif-query-planner.params
      - cloudformation/lif-query-planner-taskdef-includes.yml
      - components/lif/query_planner_service/**
      - components/lif/datatypes/**
      - components/lif/logging/**
      - projects/lif_query_planner_api/**
      - .github/workflows/_deploy-service.yml

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    uses: ./.github/workflows/_deploy-service.yml
    with:
      service_name: query-planner
      working_dir: ./projects/lif_query_planner_api
      ecr_repository: lif/dev/lif_query_planner_api
      ecs_services: '["query-planner-org1-FARGATE", "query-planner-org2-FARGATE", "query-planner-org3-FARGATE"]'
