name: Deploy LIF Orchestrator API to Amazon ECS

on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths:
      - .github/workflows/lif_orchestrator_api.yml
      - bases/lif/orchestrator_restapi/**
      - cloudformation/dev-lif-orchestrator.params
      - cloudformation/lif-orchestrator-taskdef-includes.yml
      - components/lif/datatypes/**
      - components/lif/exceptions/**
      - components/lif/logging/**
      - components/lif/orchestrator_clients/**
      - components/lif/orchestrator_service/**
      - projects/lif_orchestrator_api/**
      - .github/workflows/_deploy-service.yml

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    uses: ./.github/workflows/_deploy-service.yml
    with:
      service_name: orchestrator
      working_dir: ./projects/lif_orchestrator_api
      ecr_repository: lif/dev/lif_orchestrator
      ecs_services: '["orchestrator-FARGATE"]'
