name: Deploy LIF Translator API to Amazon ECS

on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths:
      - .github/workflows/lif_translator_api.yml
      - bases/lif/translator_restapi/**
      - cloudformation/dev-lif-translator-org1.params
      - cloudformation/lif-translator-taskdef-includes.yml
      - components/lif/exceptions/**
      - components/lif/logging/**
      - components/lif/mdr_client/**
      - components/lif/translator/**
      - projects/lif_translator_api/**
      - .github/workflows/_deploy-service.yml

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    uses: ./.github/workflows/_deploy-service.yml
    with:
      service_name: translator
      working_dir: ./projects/lif_translator_api
      ecr_repository: lif/dev/lif_translator_api
      ecs_services: '["translator-org1-FARGATE"]'
