name: Deploy LIF Query Cache API to Amazon ECS

on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths:
      - .github/workflows/lif_query_cache_api.yml
      - bases/lif/query_cache_restapi/**
      - cloudformation/dev-lif-query-cache.params
      - cloudformation/lif-query-cache-taskdef-includes.yml
      - components/lif/query_cache_service/**
      - components/lif/datatypes/**
      - components/lif/logging/**
      - components/lif/mongodb_connection/**
      - components/lif/exceptions/**
      - projects/lif_query_cache_api/**
      - .github/workflows/_deploy-service.yml

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    uses: ./.github/workflows/_deploy-service.yml
    with:
      service_name: query-cache
      working_dir: ./projects/lif_query_cache_api
      ecr_repository: lif/dev/lif_query_cache_api
      ecs_services: '["query-cache-org1-FARGATE", "query-cache-org2-FARGATE", "query-cache-org3-FARGATE"]'
