name: Deploy LIF MDR API to Amazon ECS

on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths:
      - .github/workflows/lif_mdr_api.yml
      - bases/lif/mdr_restapi/**
      - components/lif/datatypes/mdr_sqlmodel
      - components/lif/mdr_auth/**
      - components/lif/mdr_dto/**
      - components/lif/mdr_services/**
      - components/lif/mdr_utils/**
      - .github/workflows/_deploy-service.yml

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    uses: ./.github/workflows/_deploy-service.yml
    with:
      service_name: mdr-api
      working_dir: ./projects/lif_mdr_api
      ecr_repository: lif/dev/lif_mdr_api
      ecs_services: '["mdr-api-FARGATE"]'
