name: Deploy LIF Advisor API to Amazon ECS

on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths:
      - .github/workflows/lif_advisor_api.yml
      - bases/lif/advisor_restapi/**
      - cloudformation/dev-lif-advisor-api.params
      - cloudformation/lif-advisor-api-taskdef-includes.yml
      - components/lif/langchain_agent/**
      - components/lif/demo_personas/**
      - components/lif/logging/**
      - components/lif/auth/**
      - projects/lif_advisor_api/**
      - .github/workflows/_deploy-service.yml

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    uses: ./.github/workflows/_deploy-service.yml
    with:
      service_name: advisor-api
      working_dir: ./projects/lif_advisor_api
      ecr_repository: lif/dev/lif_advisor_api
      ecs_services: '["advisor-api-FARGATE"]'
