name: Deploy LIF Learner Data Export API to Amazon ECS

on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths:
      - .github/workflows/lif_learner_data_export_api.yml
      - bases/lif/learner_data_export_api/**
      - cloudformation/dev-lif-learner-data-export-api.params
      - cloudformation/lif-learner-data-export-api-taskdef-includes.yml
      - components/lif/datatypes/**
      - components/lif/exceptions/**
      - components/lif/lif_schema_config/**
      - components/lif/logging/**
      - components/lif/mdr_auth/**
      - components/lif/mdr_client/**
      - components/lif/mdr_dto/**
      - components/lif/mdr_services/**
      - components/lif/mdr_utils/**
      - components/lif/query_planner_client/**
      - components/lif/tenant_routing/**
      - components/lif/translator_client/**
      - projects/lif_learner_data_export_api/**
      - .github/workflows/_deploy-service.yml

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    uses: ./.github/workflows/_deploy-service.yml
    with:
      service_name: learner-data-export-api
      working_dir: ./projects/lif_learner_data_export_api
      ecr_repository: lif/dev/lif_learner_data_export_api
      ecs_services: '["learner-data-export-api-FARGATE"]'
