name: Deploy LIF Semantic Search MCP Server to Amazon ECS

on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths:
      - .github/workflows/lif_semantic_search_mcp_server.yml
      - bases/lif/semantic_search_mcp_server/**
      - cloudformation/dev-lif-semantic-search.params
      - cloudformation/lif-semantic-search-taskdef-includes.yml
      - components/lif/logging/**
      - components/lif/datatypes/**
      - components/lif/openapi_schema_parser/**
      - components/lif/semantic_search_service/**
      - components/lif/string_utils/**
      - components/lif/mdr_client/**
      - projects/lif_semantic_search_mcp_server/**
      - .github/workflows/_deploy-service.yml

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    uses: ./.github/workflows/_deploy-service.yml
    with:
      service_name: semantic-search-mcp
      working_dir: ./projects/lif_semantic_search_mcp_server
      ecr_repository: lif/dev/lif_semantic_search_mcp_server
      ecs_services: '["semantic-search-FARGATE"]'
      free_disk_space: true
