name: Deploy LIF Example Data Source REST API to Amazon ECS

on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths:
      - .github/workflows/lif_example_data_source_rest_api.yml
      - bases/lif/example_data_source_rest_api/**
      - cloudformation/dev-lif-example-data-source-rest-api.params
      - cloudformation/lif-example-data-source-rest-api-taskdef-includes.yml
      - components/lif/example_data_source_service/**
      - components/lif/logging/**
      - components/lif/auth/**
      - projects/lif_example_data_source_rest_api/**
      - .github/workflows/_deploy-service.yml

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    uses: ./.github/workflows/_deploy-service.yml
    with:
      service_name: example-data-source
      working_dir: ./projects/lif_example_data_source_rest_api
      ecr_repository: lif/dev/lif_example_data_source_rest_api
      ecs_services: '["example-data-source-rest-api-FARGATE"]'
