name: Deploy LIF Identity Mapper API to Amazon ECS

on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths:
      - .github/workflows/lif_identity_mapper_api.yml
      - bases/lif/identity_mapper_restapi/**
      - cloudformation/dev-lif-identity-mapper-org1.params
      - cloudformation/dev-lif-identity-mapper-org2.params
      - cloudformation/dev-lif-identity-mapper-org3.params
      - cloudformation/lif-identity-mapper-taskdef-includes.yml
      - components/lif/identity_mapper_service/**
      - components/lif/identity_mapper_storage/**
      - components/lif/identity_mapper_storage_sql/**
      - components/lif/datatypes/**
      - components/lif/logging/**
      - projects/lif_identity_mapper_api/**
      - .github/workflows/_deploy-service.yml

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    uses: ./.github/workflows/_deploy-service.yml
    with:
      service_name: identity-mapper
      working_dir: ./projects/lif_identity_mapper_api
      ecr_repository: lif/dev/lif_identity_mapper_api
      ecs_services: '["identity-mapper-org1-FARGATE", "identity-mapper-org2-FARGATE", "identity-mapper-org3-FARGATE"]'
